[env]
RUST_LOG = "nrs_webapp=debug"
SERVICE_BASE_URL = "http://localhost:3621"
SERVICE_DB_URL = "postgres://nrs_webapp_user:dev_only_pwd@localhost:3622/nrs_webapp_dev"
STATIC_SERVE_DIR = "nrs-webapp-frontend/static/serve"
IP_SOURCE = "ConnectInfo"

# app secrets, should be stored securely in prod
SERVICE_PASSWORD_PEPPER = "jIYb9KCTzZpdqbKM_e9DwcJzCefzvnAUGZzD_WH029OXbyMnn5nyUWerd_NPWrVNKKwDM6rEzmipNuFNdJ8vKej1XEb5dD2NzKwSWTNqiQKgRph6rVABcIrybPAjC31wN-7rfpQYoB1oZyYb5wl1meNgDzwjpLfpBL90R89BGx8="
SERVICE_COOKIE_KEY = "ub3lweHTzpWiVZyVrskQjcsRqRlNTFGbHMaTYec97AIFJ2wg05FYyXVjI9as9MqE19Ur5ztCWfZDPMjwxycZZlD48SeMbzH0ppxJSLgxCYTotPO79Tf1lH7IkM27ujBiiHS_MUMgFA9zKdDC9bYhHEXug6XFt-2_ZkrmNEhU_Wo="
SERVICE_SESSION_EXPIRY_SECS = "1800"

SERVICE_TOKEN_SECRET = "om2DZqcNcHWbgwH2s0obtdonH_38Ego8eMeFU58ygjFxS1u7PbSkhNdXe9bqblojmMuFfhzqljz8HEuha25AsMPyVUQ573Vsi6r8OFnI4W46JmTWI-jOk_Tto3q0Sj_9C2cWV4cJlGqQtfx5QtLbl_q78H9Y41m3ejsqxMa_Aws="
SERVICE_EMAIL_VERIFICATION_EXPIRY_SECS = "86400"
SERVICE_PASSWORD_RESET_EXPIRY_SECS = "900"

VGMDB_API_ENDPOINT = "http://localhost:2999"

GOOGLE_OAUTH_CREDENTIALS_PATH = { value = "secrets/google_oauth_credentials.json", relative = true }
